version: "3.8"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: company_profile-php
    volumes:
      - ./public:/var/www/html
      - ./php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./alice:/home/alice
      - ./bob:/home/bob
      - ./root:/root
    networks:
      - company_profile
    expose:
      - "9000"

  nginx:
    image: nginx:latest
    container_name: company_profile-nginx
    volumes:
      - ./public:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - company_profile

networks:
  company_profile:
    driver: bridge
