version: "3.8"

services:
  php:
    image: php:7.4-fpm
    container_name: company_profile-php
    volumes:
      - ./public:/var/www/html
      - ./shared-logs:/var/log/nginx
    networks:
      - company_profile
    expose:
      - "9000"

  nginx:
    image: nginx:latest
    container_name: company_profile-nginx
    volumes:
      - ./public:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./shared-logs:/var/log/nginx
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - company_profile

networks:
  company_profile:
    driver: bridge
